version: '3.8'
services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  selenium-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
      - LLM_ENDPOINT=http://host.docker.internal:11434
    ports:
      - "8080:8080"